name: Sync from MBrilla

permissions:
  contents: write

on:
  schedule:
    - cron: '0 0 * * *' # Checks for updates every day at midnight
  workflow_dispatch:    # Allows you to click "Run workflow" manually

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your fork
        uses: actions/checkout@v3
        with:
          ref: main             # Ensure your branch is named 'main'
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Add MBrilla as Upstream
        run: |
          # This sets MBrilla as the source to pull from
          git remote add upstream https://github.com/MBrilla/penguinmails.github.io.git
          git fetch upstream

      - name: Merge MBrilla's Changes
        run: |
          # Merges MBrilla/main into your current branch
          git merge upstream/main --allow-unrelated-histories

      - name: Push Changes
        run: |
          git push origin main
